# NumPy

In [1]:
import numpy as np

my_np = np.array([1, 2, 3])
print(type(my_np))
my_np

<class 'numpy.ndarray'>


array([1, 2, 3])

In [4]:
np.array([[1, 2, 3], [2, 4, 6], [3, 6, 9]])

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [13]:
np.linspace(0, 1.5, 6)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5])

In [14]:
np.random.rand(3,4)

array([[0.64150326, 0.1133851 , 0.1397873 , 0.53829952],
       [0.47091537, 0.62886243, 0.27045747, 0.37685226],
       [0.37273243, 0.27809853, 0.42093745, 0.02894371]])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.arange(24).reshape(4, 3, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [17]:
a = np.random.rand(3,4)
print("shape: ", a.shape)
print("rank: ", a.ndim)
print("rank: ", len(a.shape))
print("size: ", a.size)

shape:  (3, 4)
rank:  2
rank:  2
size:  12


In [22]:
# Examples of indexing and slicing
a = np.array([["A", "B", "C", "D"], 
              ["E", "F", "G", "H"],
              ["I", "J", "K", "L"]])
print(a)

print(a[1])
print(a[:, 1])
print(a[1, 1])
print(a[[0, 2], 1])
print(a[[0, 2], [1, 3]])
print(a[1, 1:])
print(a[1, -2:])

[['A' 'B' 'C' 'D']
 ['E' 'F' 'G' 'H']
 ['I' 'J' 'K' 'L']]
['E' 'F' 'G' 'H']
['B' 'F' 'J']
F
['B' 'J']
['B' 'L']
['F' 'G' 'H']
['G' 'H']
